package dictionary_master;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mostafa
 */
public class CreateByteCode {

//	public static void main(String args[]) throws IOException, 
//	   FileNotFoundException, UnsupportedEncodingException {
//	    createFile("AutoGenerated.java");
////	    compile(
////
////	    		);
//	}

	public static void compile(String fileName) throws IOException {
	    final String javacPath = "C:/Program Files/Java/jdk1.8.0_25/bin/javac.exe";
	    Runtime rt = Runtime.getRuntime();
	    final String compileCmd = javacPath + " " + fileName;
	    rt.exec(compileCmd);
	    
	}

	public static void createFile(String fileName,StringBuilder source) throws FileNotFoundException,
	       UnsupportedEncodingException  {
	    PrintWriter writer = new PrintWriter(fileName, "UTF-8");
	     writer.println(source.toString());
	    writer.close();
	}
	
}
