package dictionary_master;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mostafa
 */
public class CreateByteCode {

	public static void main(String args[]) throws IOException, 
	   FileNotFoundException, UnsupportedEncodingException {
	    createFile("AutoGenerated.java");
//	    compile(
//
//	    		);
	}

	public static void compile(String fileName) throws IOException {
	    final String javacPath = "C:/Program Files/Java/jdk1.8.0_25/bin/javac.exe";
	    Runtime rt = Runtime.getRuntime();
	    final String compileCmd = javacPath + " " + fileName;
	    rt.exec(compileCmd);
	    System.out.println("Hgfg");
	    
	}

	public static void createFile(String fileName) throws FileNotFoundException,
	       UnsupportedEncodingException  {
	    PrintWriter writer = new PrintWriter(fileName, "UTF-8");
	    writer.println("public class AutoGenerated");
	    writer.println("{");
	    writer.println("  public static void main(String [] args)");
	    writer.println("  {");
	    writer.println("    System.out.println(\"Hello from AutoGenerated World\");");
	    writer.println("  }");
	    writer.println("}");
	    writer.close();
	    System.out.println("Hg");
	}
	
}
